# Generated by Django 4.2.6 on 2023-12-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importador',
            fields=[
                ('id_importador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50)),
                ('representante', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('fono', models.IntegerField()),
            ],
        ),
    ]
